# Generated by Django 5.1.3 on 2024-11-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_otpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
