# Generated by Django 5.1.3 on 2024-11-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='de'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='default'),
        ),
    ]
