# Generated by Django 5.1.3 on 2024-12-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('published_at',), 'verbose_name': 'Product'},
        ),
        migrations.AddField(
            model_name='product',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
