# Generated by Django 5.1.3 on 2024-12-06 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-published_at',), 'verbose_name': 'Product'},
        ),
    ]
